version: "3"

services:
  db_postgres:
    image: postgres
    volumes:
      - "./postgres_data/postgres.conf:/usr/local/etc/postgres/postgres.conf"
      - "./schemas:/docker-entrypoint-initdb.d"
    command: "postgres -c config_file=/usr/local/etc/postgres/postgres.conf"     
    ports:
      - 5432:5432
    env_file:
      - database.env